# -*- coding: utf-8 -*-
"""Trendpluse_Task1_Final1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DCpWleZyAyHiVKRZauzleYEq11QZWKTT
"""

import requests
import time
import json
import os
from datetime import datetime

url = "https://hacker-news.firebaseio.com/v0/topstories.json"

headers = {
    "User-Agent": "TrendPulse/1.0"
}

response = requests.get(url, headers=headers)

top_story_ids = response.json()[:500]

print("Total story IDs:", len(top_story_ids))

stories = []

for story_id in top_story_ids:
    story_url = f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json"

    try:
        response = requests.get(story_url, headers=headers)

        if response.status_code == 200:
            story = response.json()

            if story:
                stories.append(story)

        else:
            print("Request failed:", story_id)

    except Exception as e:
        print("Error:", story_id, e)

print("Stories fetched:", len(stories))

categories = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}

for story in stories:
    title = story.get("title", "").lower()
    story["category"] = None

    for category, keywords in categories.items():
        if any(keyword.lower() in title for keyword in keywords):
            story["category"] = category
            break

selected_stories = []

category_count = {category: 0 for category in categories}

for story in stories:
    category = story.get("category")

    if category in category_count and category_count[category] < 25:
        selected_stories.append(story)
        category_count[category] += 1

print(category_count)
print("Total selected:", len(selected_stories))

print(selected_stories[0])

final_stories = []

for story in selected_stories:
    item = {
        "post_id": story.get("id"),
        "title": story.get("title"),
        "category": story.get("category"),
        "score": story.get("score"),
        "num_comments": story.get("descendants", 0),
        "author": story.get("by"),
        "collected_at": datetime.now().isoformat()
    }

    final_stories.append(item)

print("Final stories:", len(final_stories))
print(final_stories[0])

os.makedirs("data", exist_ok=True)

today = datetime.now().strftime("%Y%m%d")
file_path = f"data/trends_{today}.json"

with open(file_path, "w") as file:
    json.dump(final_stories, file, indent=2)

print("File saved:", file_path)

with open(file_path, "r") as file:
    check_data = json.load(file)

print("Stories in JSON:", len(check_data))
print("Fields:", list(check_data[0].keys()))

from collections import Counter

counts = Counter(story["category"] for story in final_stories)

print(counts)
print("Total:", sum(counts.values()))

from google.colab import files

files.download(file_path)

extra_url = "https://hacker-news.firebaseio.com/v0/newstories.json"

response = requests.get(extra_url, headers=headers)
extra_ids = response.json()[:500]

print("Extra story IDs:", len(extra_ids))

extra_stories = []

for story_id in extra_ids:
    story_url = f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json"

    try:
        response = requests.get(story_url, headers=headers)

        if response.status_code == 200:
            story = response.json()

            if story:
                extra_stories.append(story)

    except Exception as e:
        print("Error:", story_id, e)

print("Extra stories fetched:", len(extra_stories))

for story in extra_stories:
    title = story.get("title", "").lower()
    story["category"] = None

    for category, keywords in categories.items():
        if any(keyword.lower() in title for keyword in keywords):
            story["category"] = category
            break

print("Category assignment completed")

extra_count = Counter(
    story["category"]
    for story in extra_stories
    if story.get("category")
)

print(extra_count)

combined_stories = stories + extra_stories

selected_stories = []
category_count = {category: 0 for category in categories}

for story in combined_stories:
    category = story.get("category")

    if category in category_count and category_count[category] < 25:
        selected_stories.append(story)
        category_count[category] += 1

print(category_count)
print("Total selected:", len(selected_stories))

final_stories = []

for story in selected_stories:
    item = {
        "post_id": story.get("id"),
        "title": story.get("title"),
        "category": story.get("category"),
        "score": story.get("score"),
        "num_comments": story.get("descendants", 0),
        "author": story.get("by"),
        "collected_at": datetime.now().isoformat()
    }

    final_stories.append(item)

print("Final stories:", len(final_stories))

today = datetime.now().strftime("%Y%m%d")
file_path = f"data/trends_{today}.json"

with open(file_path, "w") as file:
    json.dump(final_stories, file, indent=2)

print("File saved:", file_path)
print("Stories saved:", len(final_stories))

with open(file_path, "r") as file:
    check_data = json.load(file)

print("Stories in JSON:", len(check_data))
print("Fields:", list(check_data[0].keys()))

import pandas as pd
import json

file_path = "data/trends_20260927.json"

with open(file_path, "r") as file:
  data = json.load(file)
  print("Stories loaded:", len(data))

df = pd.DataFrame(data)

print("Rows:", len(df))
print("Columns:", list(df.columns))

print("missing values:")
print(df.isnull().sum())

print("Duplicate rows:", df.duplicated().sum())

print(df.dtypes)

df["collected_at"] = pd.to_datetime(df["collected_at"])

print(df.dtypes)

print(df["category"].value_counts())

print(df["category"].value_counts())

import pandas as pd

df = pd.read_json(file_path)

print("Rows:", len(df))
print("Columns:", list(df.columns))

print("Missing values:")
print(df.isnull().sum())

print("Duplicate rows:", df.duplicated().sum())

print("Data types:")
print(df.dtypes)

df["collected_at"] = pd.to_datetime(df["collected_at"])

df["score"] = pd.to_numeric(df["score"])
df["num_comments"] = pd.to_numeric(df["num_comments"])

print(df.dtypes)

output_path = "data/cleaned_trends.csv"

df.to_csv(output_path, index=False)

print("CSV saved:", output_path)
print("Rows saved:", len(df))

output_path = "data/cleaned_trends.csv"

df.to_csv(output_path, index=False)

print("CSV saved:", output_path)
print("Rows saved:", len(df))

category_summary = df.groupby("category")["score"].agg(["count", "mean", "max"])

print(category_summary)

category_summary.sort_values("mean", ascending=False)

import matplotlib.pyplot as plt

category_summary["mean"].plot(kind="bar")

plt.title("Average Score by Category")
plt.xlabel("Category")
plt.ylabel("Average Score")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.hist(df["score"], bins=10)

plt.title("Distribution of Story Scores")
plt.xlabel("Score")
plt.ylabel("Number of Stories")
plt.tight_layout()
plt.show()

plt.hist(df["score"], bins=10)

plt.title("Distribution of Story Scores")
plt.xlabel("Score")
plt.ylabel("Number of Stories")
plt.tight_layout()
plt.show()

plt.hist(df["score"], bins=10)

plt.title("Distribution of Story Scores")
plt.xlabel("Score")
plt.ylabel("Number of Stories")
plt.tight_layout()
plt.show()

plt.savefig("trending_scores.png")
print("Chart saved successfully")